/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedFerramentasRouteImport } from './routes/_authed/ferramentas'
import { Route as AuthedPainelRouteImport } from './routes/_authed/painel'
import { Route as AuthedProjetosIndexRouteImport } from './routes/_authed/projetos/index'
import { Route as AuthedProjetosProjetoIdRouteImport } from './routes/_authed/projetos/$projetoId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFerramentasRoute = AuthedFerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPainelRoute = AuthedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjetosIndexRoute = AuthedProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjetosProjetoIdRoute = AuthedProjetosProjetoIdRouteImport.update({
  id: '/projetos/$projetoId',
  path: '/projetos/$projetoId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/ferramentas': typeof AuthedFerramentasRoute
  '/painel': typeof AuthedPainelRoute
  '/projetos/$projetoId': typeof AuthedProjetosProjetoIdRoute
  '/projetos/': typeof AuthedProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/ferramentas': typeof AuthedFerramentasRoute
  '/painel': typeof AuthedPainelRoute
  '/': typeof AuthedIndexRoute
  '/projetos/$projetoId': typeof AuthedProjetosProjetoIdRoute
  '/projetos': typeof AuthedProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/ferramentas': typeof AuthedFerramentasRoute
  '/_authed/painel': typeof AuthedPainelRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/projetos/$projetoId': typeof AuthedProjetosProjetoIdRoute
  '/_authed/projetos/': typeof AuthedProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ferramentas'
    | '/painel'
    | '/projetos/$projetoId'
    | '/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/ferramentas'
    | '/painel'
    | '/'
    | '/projetos/$projetoId'
    | '/projetos'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/ferramentas'
    | '/_authed/painel'
    | '/_authed/'
    | '/_authed/projetos/$projetoId'
    | '/_authed/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ferramentas': {
      id: '/_authed/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof AuthedFerramentasRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/painel': {
      id: '/_authed/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthedPainelRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projetos/': {
      id: '/_authed/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof AuthedProjetosIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projetos/$projetoId': {
      id: '/_authed/projetos/$projetoId'
      path: '/projetos/$projetoId'
      fullPath: '/projetos/$projetoId'
      preLoaderRoute: typeof AuthedProjetosProjetoIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedFerramentasRoute: typeof AuthedFerramentasRoute
  AuthedPainelRoute: typeof AuthedPainelRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedProjetosProjetoIdRoute: typeof AuthedProjetosProjetoIdRoute
  AuthedProjetosIndexRoute: typeof AuthedProjetosIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedFerramentasRoute: AuthedFerramentasRoute,
  AuthedPainelRoute: AuthedPainelRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedProjetosProjetoIdRoute: AuthedProjetosProjetoIdRoute,
  AuthedProjetosIndexRoute: AuthedProjetosIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
